# array of RegExp strings to match workflow names
# which should be watched by bot
workflowWithTests = [
    '.*E2E*', # all workflows with sub-string "e2e" in their names will be watched by bot
]

# array of RegExp strings to match images inside artifacts (by their path or file name)
# which shows difference between two screenshot and which will be added to bot report comment
screenshotsDiffsPaths = [
    '.*__diff_output__.*', # it is default cypress folder name into which snapshot diffs are put
    '.*.diff.png'
]

# RegExp string to match images inside artifacts (by their path or file name)
# which are created by new screenshot tests.
newScreenshotMark = '.*==new==.*'

# array of RegExp strings to match branch names which should be skipped by bot
branchesIgnore = ["^release/.*", "^v[0-9].x$"]

# array of attributes (key="value") for html-tag <img /> (screenshots)
screenshotImageAttrs = []

# Text which is placed at the beginning of section "Failed tests"
failedTestsReportDescription = '<h3 align="center">Before (main) ← Diff → After (local)</h3>'
