import taiga from '@taiga-ui/eslint-plugin-experience-next';

export default [
    ...taiga.configs.recommended,
    ...taiga.configs['taiga-specific'],
    {
        files: ['**/*.html'],
        rules: {
            '@angular-eslint/template/elements-content': 'off',
            '@angular-eslint/template/button-has-type': [
                'error',
                {
                    ignoreWithDirectives: [
                        'tuiAccordion',
                        'tuiOption',
                        'tuiTab',
                        // Buttons
                        'tuiBoldTool',
                        'tuiItalicTool',
                        'tuiUnderlineTool',
                        'tuiStrikeTool',
                        'tuiFontStyleTool',
                        'tuiFontSizeTool',
                        'tuiAlignTool',
                        'tuiAlignLeftTool',
                        'tuiAlignCenterTool',
                        'tuiAlignJustifyTool',
                        'tuiAlignRightTool',
                        'tuiAnchorTool',
                        'tuiAttachTool',
                        'tuiClearTool',
                        'tuiCodeTool',
                        'tuiDetailsAddTool',
                        'tuiDetailsRemoveTool',
                        'tuiInsertGroupTool',
                        'tuiRemoveGroupTool',
                        'tuiHighlightColorTool',
                        'tuiHrTool',
                        'tuiImageTool',
                        'tuiLinkTool',
                        'tuiUnorderedListTool',
                        'tuiOrderedListTool',
                        'tuiTaskListTool',
                        'tuiIndentTool',
                        'tuiOutdentTool',
                        'tuiListTool',
                        'tuiBlockquoteTool',
                        'tuiRedoTool',
                        'tuiUndoTool',
                        'tuiSubscriptTool',
                        'tuiSuperscriptTool',
                        'tuiPaintTool',
                        'tuiInsertTableTool',
                        'tuiTableMergeCellTool',
                        'tuiTexTool',
                        'tuiTextColorTool',
                        'tuiAddRowTableTool',
                    ],
                },
            ],
        },
    },
    {ignores: ['.release-it.js', '**/tests-results/*']},
];
