import {TuiEditorTool} from '../types/editor-tool';

export const TUI_EDITOR_DEFAULT_TOOLS = new Set([
    TuiEditorTool.Undo,
    TuiEditorTool.Size,
    TuiEditorTool.Bold,
    TuiEditorTool.Italic,
    TuiEditorTool.Underline,
    TuiEditorTool.Align,
    TuiEditorTool.List,
    TuiEditorTool.Quote,
    TuiEditorTool.Link,
    TuiEditorTool.Anchor,
    TuiEditorTool.Color,
    TuiEditorTool.Hilite,
    TuiEditorTool.Clear,
    TuiEditorTool.Strikethrough,
    TuiEditorTool.Code,
    TuiEditorTool.Img,
    TuiEditorTool.HR,
    TuiEditorTool.Sup,
    TuiEditorTool.Sub,
    TuiEditorTool.Table,
    TuiEditorTool.CellColor,
    TuiEditorTool.Details,
]);
