// eslint-disable-next-line no-restricted-syntax
export const enum TuiDemoPath {
    Stackblitz = `stackblitz`,
    Changelog = `changelog`,
    StarterKit = `starter-kit`,
    ColorPicker = `color-picker`,
    Font = `font`,
    Anchors = `anchors`,
    Groups = `groups`,
    Focus = `focus`,
    UploadFiles = `upload-files`,
    PasteEmojiTool = `custom-tool/paste-emoji`,
    ColorPickerTool = `custom-tool/color-picker`,
    PasteImageTool = `custom-tool/paste-image`,
    HighlightText = `highlight/text`,
    HighlightCode = `highlight/code`,
    ProcessingLegacyHtml = `processing/legacy-html`,
    ProcessingCleanupHtml = `processing/cleanup-html`,
    ProcessingMarkdown = `processing/markdown`,
    ImagesResizable = `images/resizable`,
    ImagesPreview = `images/preview`,
    ImagesUpload = `images/upload`,
    EmbedYoutube = `embed/youtube`,
    EmbedIframe = `embed/iframe`,
    EmbedHtml5 = `embed/html5`,
}
