// eslint-disable-next-line no-restricted-syntax
export const enum TuiDemoPath {
    StarterKit = `starter-kit`,
    Installation = `installation`,
    Font = `font`,
    Anchors = `anchors`,
    Groups = `groups`,
    Focus = `focus`,
    UploadFiles = `upload-files`,
    PasteEmoji = `custom-tool/paste-emoji`,
    ColorPicker = `custom-tool/color-picker`,
    PasteImage = `custom-tool/paste-image`,
    HighlightText = `highlight/text`,
    HighlightCode = `highlight/code`,
    ProcessingLegacyHtml = `processing/legacy-html`,
    ProcessingCleanupHtml = `processing/cleanup-html`,
    ProcessingMarkdown = `processing/markdown`,
    ImagesResizable = `images/resizable`,
    ImagesPreview = `images/preview`,
    ImagesUpload = `images/upload`,
    EmbedYoutube = `embed/youtube`,
    EmbedIframe = `embed/iframe`,
    EmbedHtml5 = `embed/html5`,
    Changelog = `changelog`,
}
