// TODO: change type in v4.0
// eslint-disable-next-line no-restricted-syntax
export enum TuiEditorTool {
    Align = 'justify',
    Anchor = 'anchor',
    Attach = 'attach',
    Bold = 'bold',
    Clear = 'clear',
    Code = 'code',
    Color = 'foreColor',
    Details = 'details',
    Group = 'group',
    HR = 'insertHorizontalRule',
    Hilite = 'hiliteColor',
    Img = 'image',
    Italic = 'italic',
    Link = 'link',
    List = 'list',
    MergeCells = 'mergeCells',
    Quote = 'quote',
    RowsColumnsManaging = 'rowsColumnsManaging',
    Size = 'fontSize',
    SplitCells = 'splitCells',
    Strikethrough = 'strikeThrough',
    Sub = 'subscript',
    Sup = 'superscript',
    Table = 'insertTable',
    Tex = 'tex', // Todo
    Underline = 'underline',
    Undo = 'undo',
}
