export const TuiEditorTool = {
    Align: 'justify',
    Anchor: 'anchor',
    Attach: 'attach',
    Bold: 'bold',
    Clear: 'clear',
    Code: 'code',
    Color: 'foreColor',
    Details: 'details',
    Group: 'group',
    HR: 'insertHorizontalRule',
    Hilite: 'hiliteColor',
    Img: 'image',
    Italic: 'italic',
    Link: 'link',
    List: 'list',
    MergeCells: 'mergeCells',
    Quote: 'quote',
    RowsColumnsManaging: 'rowsColumnsManaging',
    Size: 'fontSize',
    SplitCells: 'splitCells',
    Strikethrough: 'strikeThrough',
    Sub: 'subscript',
    Sup: 'superscript',
    Table: 'insertTable',
    CellColor: 'cellColor',
    Tex: 'tex',
    Underline: 'underline',
    Undo: 'undo',
} as const;

export type TuiEditorToolType = (typeof TuiEditorTool)[keyof typeof TuiEditorTool];
