name: 🚀 Deploy
on: pull_request

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: taiga-family/actions/setup-variables@a6230c2ffdf53253580ec058dd4faccdb01ac85a # v2.4.0
      - uses: taiga-family/actions/setup-node@a6230c2ffdf53253580ec058dd4faccdb01ac85a # v2.4.0
      - run: npx nx build editor-demo
      - run: npx --yes bundlemon --config .github/.bundlemonrc.json
      - uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a # v0.11.0
        continue-on-error: true
        if: ${{ env.IS_FORK == 'false' && env.IS_DEPENDABOT == 'false' }}
        with:
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TUI_EDITOR }}
          channelId: pr${{ github.event.number }}-${{ github.head_ref }}-demo
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          projectId: taiga-editor
          target: taiga-editor
          expires: 1d

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
