name: ⚙️ Tests
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: taiga-family/actions/setup-variables@b0e21e793cde96d90c7fa5adb97f1c59a2f6d85b # v2.17.0
      - uses: taiga-family/actions/setup-node@b0e21e793cde96d90c7fa5adb97f1c59a2f6d85b # v2.17.0
      - run: npm run test
      - uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          directory: ./coverage/editor
          flags: editor
          name: editor

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
